language: python
python:
  - "2.7"
  - "3.2"
install:
  - python setup.py install
  - pip install nose
script:
  - nosetests -e test_with_fix -e test_main --with-doctest --with-xunit test
notifications:
  email: false
